# -*- coding: utf-8 -*-
"""Untitled31.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18KAoHnZkZrn5ONTgn6vY3leHsUtpI6_e
"""

class Perpustakaan :
    def __init__(self, judul, tentang, subjek, lokasi, info) :
        self.judul = judul
        self.tentang =  tentang
        self.subjek = subjek
        self.lokasi = lokasi
        self.info = info

class Buku(Perpustakaan) :
    def __init__(self, judul, tentang, subjek, lokasi, info, isbn, pengarang, jmlhal, totalpeminjam):
        super().__init__(judul, tentang, subjek, lokasi, info)
        self.isbn = isbn
        self.pengarang = pengarang
        self.jmlhal = jmlhal       
        self.totalpeminjam = totalpeminjam         

class Majalah(Perpustakaan) :
    def __init__(self, judul, tentang, subjek, lokasi, info, volume, issue):
        super().__init__(judul, tentang, subjek, lokasi, info)
        self.volume = volume
        self.issue = issue

class DVD(Perpustakaan) :
    def __init__(self, judul, tentang, subjek, lokasi, info, aktor, genre):
        super().__init__(judul, tentang, subjek, lokasi, info)
        self.aktor = aktor
        self.genre = genre    

buku = Buku("Ada Akku Disini", "Percintaan", "Buku", "Rak 19", "Ada", "978-234-78-8", "Hawwen Harvard", 20, 12)
majalah = Majalah("Hiphop Klasik", "Musik", "Majalah", "Rak 8", "Dipinjam", "Vol 8", "1001")
dvd = DVD("Bagio sang Pengembala", "Legenda", "Copy", "Rak 10", "Dipinjam", "Marmin", "Dongeng")

kategori = [buku, majalah, dvd] 

for object in kategori : 
    print(f"Judul : {object.judul}")
    print(f"Tentang : {object.tentang}")
    print(f"Subjek : {object.subjek}")
    print(f"Letak : {object.lokasi}") 
    print(f"Info : {object.info}\n")