# -*- coding: utf-8 -*-
"""Untitled34.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lIuS-LM6LDkXmOXxIRnJhu9R5ak2tqWY
"""

import os
def perpusItem (msg):
  input(msg)
  if os.name == "posix":
    os.system("clear")
  else:
    os.system("cls")

def mainMenu(x):
  if x == "1":
    readal1()

  elif x == "2":
    judul = input("Masukan Judul Buku : ")
    create(judul)

  elif x == "3":
    judul = input("Masukan Judul Yang Dicari : ")
    readone(judul)

  elif x == "4":
    judul = input("Masukan Judul Yang Dicari : ")
    delete(judul)

  elif x == "5":
    print("Exit Progam Perpustakaan")

  else:
    print("Option Not Found.")

def create(judul):
  buku.append(judul)
  perpusItem("Data berhasil ditambahkan, Masukan Angka Menu untuk Melanjutkan")

def readal1():
  print("Daftar Buku : ")
  no = 1
  for i in buku:
    print(str(no)+","+i)
    no +=1
    perpusItem("Masukan Angka Menu untuk Melanjutkan")

def readone(judul):
  filter_object = filter(lambda a: judul in a, buku)
  p = list(filter_object)
  if(not p):
    perpusItem("Data tidak ditemukan, Masukan Angka Menu untuk Melanjutkan")
  else:
    perpusItem("Buku berjudul '"+",".join(p)+"' berhasil ditemukan.")

def delete(judul):
  if buku.count(judul) >= 1:
    buku.remove(judul)
    perpusItem("Data berhasil dihapus, Masukan Angka Menu untuk Melanjutkan")
  else: 
    perpusItem("Buku tidak ditemukan.Harap mengetik secara detail untuk keamanan.")

buku = ["Bagio sang Pengembala", "Hip-Hop klasik", "Ada aku disini"]

x = "0"
while x != "5":
  print("Program Perpustakaan UTY")
  print("[1] Tampilkan Semua Data Buku")
  print("[2] Tambahkan Data Buku")
  print("[3] Cari Buku")
  print("[4] Hapus Buku")
  print("[5] Exit")
  print()

  x = input("Pilihan : ")
  mainMenu(x)