# -*- coding: utf-8 -*-
"""PBO 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mkSZanLuH5lzmTzvVqWIMmJyjc28Pb3v

PBO TUGAS 2 

SHENDY FACHRIAN MAULANA

5210411225
"""

str='aku cinta indonesia'
print(str)

str= str[:10]+"tanah air ku"+str[9:]
print(str)

str=''
print(str)

str1="aku cinta tanah air ku indonesia"
str1=str1[:9]+''+str1[22:]
print(str1)

kelas='Praktikum pemrograman berorientasi objek'
up=kelas.upper()
lo=kelas.lower()
print(kelas)
print(up)
print(lo)

s='     Python     '
s.strip()
s.lstrip()
s.rstrip()

len(kelas)

jumlah=len(kelas)
print('panjang string adalah: ', jumlah)

s1='Python'
s2='Progamming'
s1+s2

kelas
print(kelas.index('a'))

kelas2=kelas.replace('Praktikum','praktik')
print(kelas2)

a='satu'
b='dua'
c='tiga'
print('saya mempunyai %s mangga'%(b))

kelas2
kelas2.split()

input('hari ini adalah: ')

data1=input("angka 1:")
data2=input("angkaa 2:")
hasil=int(data1)*int(data2)
print(data1,"*",data2," = ",hasil)

list=[0,1,2,3,4,5,6,7,8,9]
print(list)
print(list[0])
print(list[5])
print(list[:3])

len(list)
print(list[10-3:])
print(list[2:9])
print(list[-10])
print(list[0])

list.append(10)
list

list.insert(1,11)
list

list2=['halo']
list.extend(list2)
list

list.extend('hai')
list

del list[1]
list

list.remove(10)
list

list.pop()
list

list.pop(2)
list

a=[50,10,20,30,40]
b=sorted(a)
b

a
a.sort()
a

a.sort(reverse=True)
a

a=[50,10,20,30,40]
min(a)

a=[50,10,20,30,40]
max(a)

d={1:100, 2:200, 3:300, 4:400, 5:500}
print(d)
d[2]

d.get(4)

d.keys()

d.values()

d={1:100, 2:200, 3:300, 4:400, 5:500}
print(d)

del d[1]
print(d)

b=d.copy()
print(b)

d.clear()
print(d)

len(d)

t=(100,200,300,400)
print(t)

t[0]

t[3]

t.index(200)

t2=(10,20,10,10,30,10,40,20)
t.count(10)

t2=(10,20,10,10,30,10,40,20)
t2.count(20)
t2.count(10)
t.count(30)
t2.count(20)

"""TUGAS PBO PRAKTEK LANJUTAN DARI PRAKTIKUM HARI INI  DITAMBAH DENGAN SET ATAU HIMPUNAN"""

# FUNSI ADD() dan UPDATE()

nama = {'s','h','e','n','d'}
print(nama)

nama.add(10)
print(nama)

nama.update([1,2,3])
print(nama)

# FUNGSI DISCARD() dan REMOVE()

data = {'a','b','c','d',1,2,3,4}
print(data)

data.remove(3)
print(data)

data.discard(5)
print(data)

# FUNGSI UNION()

Npm1 = {225,223,220}
Npm2 = {228,321,290}

Npm3 = Npm1.union(Npm2)
print(Npm3)

# FUNGSI INTERSECTION(), DIFFERENCE() dan SYMMETRIC_DIFFERENCE()
data1 = {1,2,3,4}
data2 = {1,2,7,8}

data3 = data1.intersection(data2)
print(data3)

data3 = data1.difference(data2)
print (data3)

data3 = data1.symmetric_difference(data2)
print (data3)

# FUNGSI CLEAR()
Klub_bola = {"Juventus", "BArcelona", "Milan"}
print(Klub_bola)

Klub_bola.clear()
print(Klub_bola)

# FUNGSI COPY() dan  REMOVE()

makanan_khas = {'gudek', 'kerak telor', 'karedok'}

makanan_enak = makanan_khas.copy()
print("Makanan khas : ",makanan_khas)
print("Makanan enak : ",makanan_enak)

makanan_enak.remove('gudek')
print(makanan_enak)

# FUNGSI DIFFERENCE_UPDATE() dan POP()

Angka1 = {2, 3, 4, 5, 6, 7}
Angka2 = {10, 2, 4, 11, 5, 45}

Angka1.difference_update(Angka2)
print(Angka1)

nilaipop = Angka1.pop()
print(nilaipop)

