# -*- coding: utf-8 -*-
"""Untitled35.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UGh4RuXqsqlf3ftwk4YFXjzZMkkhqAZK
"""

class Gaji:
    def __init__(self,gajiBulanan):
        self.gajiBulanan = gajiBulanan
    
    def total(self):
        return (self.gajiBulanan*12)

class Pegawai:
    def __init__(self,gajiBulanan, bonus, istri, anak):
        self.gajiBulanan = gajiBulanan
        self.tunjangan = istri + anak
        self.bonus = bonus
        self.obj_gaji = Gaji(self.gajiBulanan)
        
    def hasil_setahun(self):
        return "Total: " + str(self.obj_gaji.total() + self.bonus) + 'rupiah' + "\nTunjangan Anak dan Istri: " + str(self.tunjangan) + ' rupiah'

print("Input Data Pegawai")
print("-"*40)
gaji_input = int(input("Masukan Gaji Pegawai1: "))    
bonus_input = int(input("Masukan Bonus Pegawai: "))  
tunjangan_istri = int(input("Masukan Tunjangan Istri Pegawai: "))  
tunjangan_anak = int(input("Masukan Tunjangan Anak Pegawai: ")) 
print("-"*40) 
obj_pegawai = Pegawai(gaji_input,bonus_input,tunjangan_istri,tunjangan_anak)
print(obj_pegawai.hasil_setahun())