# -*- coding: utf-8 -*-
"""Pbo6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16IdHQ2rF1ZqSvvaG3QRkDVp4bEDk8yz_
"""

#LATIHAN
class Titik:
  def __init__(self,x,y):
    self.x = x
    self.y = y

titik_a = Titik(0,3)
titik_b = Titik(5,4)
print('Titik A memiliki koordinat ({},{})'.format(titik_a.x,titik_a.y))
print('Titik B memiliki koordinat ({},{})'.format(titik_b.x,titik_b.y))

class MenuMinuman:
  def __init__(self,nama,deskripsi,harga):
        self.nama = nama
        self.deskripsi = deskripsi 
        self.harga = harga

mnm1 = MenuMinuman("Jus jambu","Jus jambu merah tanpa gula",8500)
mnm2 = MenuMinuman("Jus alpukat Ori","Jus alpukat dengan tambahan air gula merah", 1500) 
mnm3 = MenuMinuman("Jus alpukat xtra milk","Jus alpukat dengan campuran susu coklat dan taburan kepingan choco", 15000)
mnm4 = MenuMinuman("Red & Smooth","Smoothie pisang susu dengan strawberry",17500)

pilihan_minuman = [mnm1,mnm2,mnm3,mnm4]
print("Daftar menu Healty Fruits")
for mn in pilihan_minuman:
   t = "{} harga Rp {}, {}".format(mn.nama,mn.harga,mn.deskripsi)
   print(t)

class Buku:
  def __init__(self,judul,pengarang,tahun_terbit):
        self.judul = judul
        self.pengarang = pengarang
        self.tahun_terbit = tahun_terbit

buku = Buku("Tenggelamnya Kapal Van der Wijck", "HAMKA", 1938)
t = "Buku {} karangan {} pertama kali diterbitkan tahun {}".format(buku.judul,buku.pengarang,buku.tahun_terbit)
print(t)

#titik dibentuk posisi pada sumbu x dan y
class Titik:
    def __init__(self,x,y):
        self.x = x
        self.y = y

#garis dibentuk dari dua titik
class garis:
    def __init__(self,titik_pertama,titik_kedua):
        self.titik_pertama = titik_pertama
        self.titik_kedua = titik_kedua

    def panjang(self):
        pjg_x = self.titik_kedua.x - self.titik_pertama.x
        pjg_y = self.titik_kedua.y - self.titik_pertama.y
        pjg = (pjg_x**2 + pjg_y**2) ** 0.5
        return pjg

titik_a =  Titik(0,0)
titik_b = Titik(3,4)
garis_ab = garis(titik_a,titik_b)
print("Panjang garis AB adalah {}".format(garis_ab.panjang()))

class Mahasiswa:
  def __init__(self,nama,nim,prodi,thn_masuk):
    self.nama = nama
    self.nim = nim
    self.prodi = prodi
    self.thn_masuk = thn_masuk
m1 = Mahasiswa('Udin','10120371','Sistem Informasi',2020)
teks = '{} adalah mahasiswa {} angkatan {} dengan NIM {}'.format(m1.nama,m1.prodi,m1.thn_masuk,m1.nim)
print(teks)

#TUGAS 

class MenuMinuman:
  def __init__(self,nama,deskripsi,harga):
        self.nama = nama
        self.deskripsi = deskripsi 
        self.harga = harga

mnm1 = MenuMinuman("Jus jambu","Jus jambu merah tanpa gula",8500)
mnm2 = MenuMinuman("Jus alpukat Ori","Jus alpukat dengan tambahan air gula merah", 1500) 
mnm3 = MenuMinuman("Jus alpukat xtra milk","Jus alpukat dengan campuran susu coklat dan taburan kepingan choco", 15000)
mnm4 = MenuMinuman("Red & Smooth","Smoothie pisang susu dengan strawberry",17500)
mnm5 = MenuMinuman("Lasegar","Minuman kaleng dengan rasa asli buah",7000)
mnm6 = MenuMinuman("Air kelapa ijo","Air kelapa muda segar seribu khasiat",10000)


pilihan_minuman = [mnm1,mnm2,mnm3,mnm4]
print("Daftar menu Healty Fruits")

for i in pilihan_minuman:
   t = "{} harga Rp {}, {}".format(i.nama,i.harga,i.deskripsi)
   print(t)

class Mahasiswa:
  def __init__(self,nama,nim,prodi,thn_masuk):
    self.nama = nama
    self.nim = nim
    self.prodi = prodi
    self.thn_masuk = thn_masuk
    
m1 = Mahasiswa('Udin','10120371','Sistem Informasi',2020)
m2 = Mahasiswa('Fachrian','52107889','Sastra',2019)
m3 = Mahasiswa('Shendy','2345679','Informatika',2021)

dataMahasiswa = [m1,m2,m3]
for i in dataMahasiswa:
  print('nama {} dengan nim {} jurusan {} tahun masuk {}'.format(i.nama,i.nim,i.prodi,i.thn_masuk))

class Buku:
  def __init__(self,judul,pengarang,tahun_terbit):
        self.judul = judul
        self.pengarang = pengarang
        self.tahun_terbit = tahun_terbit

buku = Buku("Tenggelamnya Kapal Van der Wijck", "HAMKA", 1938)
buku1 = Buku("Matahari tersenyum llebar","fachrianshendy",2000)
buku2 = Buku("Piknik Seru",'Anita Hairunnisa',2009)

daftar_buku = [buku,buku1,buku2]
for x in daftar_buku:
  print('buku {} karangan dari {} pertama kali di terbitkan pada tahun {}'.format(x.judul,x.pengarang,x.tahun_terbit))