# -*- coding: utf-8 -*-
"""Pbo T 5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g573Ca7hjV63r8py016F1o00n4EFMpU4
"""

class ComputerPart():  
  def __init__(self,pabrikan,nama,jenis): 
    self.pabrikan = pabrikan 
    self.nama = nama 
    self.jenis = jenis 

class CentralProcessingUnit(ComputerPart): 
  def __init__(self,pabrikan,nama,harga): 
    super().__init__(pabrikan,nama,'CPU') 

class RandomAccesMemory(CentralProcessingUnit): 
  def __init__(self,pabrikan,nama,harga): 
    super().__init__(pabrikan,nama,'RAM') 

class HardDiskSATA(RandomAccesMemory): 
  def __init__(self,pabrikan,nama): 
    super().__init__(pabrikan,nama,'SATA')

pc = ComputerPart('','PC GAMING SATRIA R','') 
cpu = CentralProcessingUnit('','IntelCore i7 7740X 4,3GHz',0) 
ram = RandomAccesMemory('','V-Gen DDR4 SODimm PC19200/2400MHz',0) 
hdd = HardDiskSATA('','Seagate HDD 2.5 inch 500GB') 

print(pc.nama)
print(cpu.nama)
print(ram.nama)
print(hdd.nama)

#HIERARCHICAL INHERITANCE

class ComputerPart(): 
  def __init__(self,pabrikan,nama,jenis): 
    self.pabrikan = pabrikan 
    self.nama = nama 
    self.jenis = jenis
  
class CentralProcessingUnit(ComputerPart): 
  def __init__(self,pabrikan,nama,harga,kapasitas): 
    super().__init__(pabrikan,nama,'CPU') 
    self.kapasitas = kapasitas 
  def harga_cpu(self):
    print('Harga: Rp 3.000.000')

class GraphicsCard(ComputerPart):
  def __init__(self,pabrikan,nama,harga,kapasitas): 
    super().__init__(pabrikan,nama,'VGA') 
    self.kapasitas = kapasitas 
  def harga_vga(self): 
    print('Harga: Rp 3.150.000')

class RandomAccesMemory(ComputerPart):
  def __init__(self,pabrikan,nama,harga,kapasitas): 
    super().__init__(pabrikan,nama,'RAM') 
    self.kapasitas = kapasitas 
  def harga_ram(self): 
    print('Harga: Rp 2.000.000')

class HardDiskSATA(ComputerPart): 
  def __init__(self,pabrikan,nama,kapasitas,rpm): 
    super().__init__(pabrikan,nama,'SATA') 
    self.kapasitas = kapasitas 
    self.rpm = rpm 
  def harga_hdd(self): 
    print('Harga: Rp 1.250.000')

cpu = CentralProcessingUnit('','Intel Core i7 7740x 4.3GHz',0,'')
vga = GraphicsCard('','NVIDIA RTX 3080 TI 35000000 12 1670',0,'') 
ram = RandomAccesMemory('','V-Gen DDR4 SODimm PC19200/2400MHz',0,'') 
hdd = HardDiskSATA('','Seagate HDD 2.5 inch 500GB',0,'') 


print(cpu.nama)
cpu.harga_cpu()
print(vga.nama)
vga.harga_vga()
print(ram.nama)
ram.harga_ram()
print(hdd.nama)
hdd.harga_hdd()

#MUTIPLE INHERITANCE

class CentralProcessingUnit(): 
  def __init__(self,nama_cpu,harga_cpu): 
    self.nama_cpu = nama_cpu 
    self.harga_cpu = harga_cpu

class  GraphicsCard():
  def __init__(self,nama_vga,harga_vga): 
    self.nama_vga = nama_vga 
    self.harga_vga = harga_vga 

class RandomAccesMemory(): 
  def __init__(self,nama_ram,harga_ram): 
    self.nama_ram = nama_ram 
    self.harga_ram = harga_ram 

class HardDiskSATA(): 
  def __init__(self,nama_hdd,harga_hdd): 
    self.nama_hdd = nama_hdd 
    self.harga_hdd = harga_hdd 


class ComputerPart(CentralProcessingUnit,GraphicsCard,RandomAccesMemory,HardDiskSATA): 
  def __init__(self,nama_cpu,harga_cpu,nama_vga,harga_vga,nama_ram,harga_ram,nama_hdd,harga_hdd): 
    CentralProcessingUnit.__init__(self,nama_cpu,harga_cpu) 
    GraphicsCard.__init__(self,nama_vga,harga_vga) 
    RandomAccesMemory.__init__(self,nama_ram,harga_ram) 
    HardDiskSATA.__init__(self,nama_hdd,harga_hdd) 


pc = ComputerPart('Intel Core i 7740x 4.3GHz','Rp 3.000.000','NVIDIA RTX 3080 TI 35000000 12 1670','Rp 3.150.000','V-Gen DDR4 SODimm PC19200/2400MHz','Rp 2.000.000','Seagate HDD 2.5 inch 500GB','Rp 1.250.000')

print(pc.nama_cpu,pc.harga_cpu)
print(pc.nama_vga,pc.harga_vga)
print(pc.nama_ram,pc.harga_ram)
print(pc.nama_hdd,pc.harga_hdd)