# -*- coding: utf-8 -*-
"""PBO8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BXyNpndeX9DXB8vNZmh_De7e-oP20qrr
"""

#PUBLIC

class Segitiga:
  def __init__(self,alas,tinggi):
    self.alas= alas
    self.tinggi = tinggi
    self.luas = 0.5 * alas * tinggi
  
segitiga_besar = Segitiga(100,80)

print("Alas: ",segitiga_besar.alas)
print("Tinggi: ",segitiga_besar.tinggi)
print("Luas: ",segitiga_besar.luas)

#PROTECTED

class Utama:
  def __init__(self):
    self._a = 2

class Turunan(Utama):
  def __init__(self):
    Utama.__init__(self)
    print("Memanggil variabel protected pada class Utama: ",self._a)

    self._a = 3
    print("Memanggil variabel protected yang dimodifikasi diluar class: ",self._a)

objek1 = Turunan()
objek2 = Utama()

print("Mengakses variabel protected dari objek1: ",objek1._a)
print("Mengakses variabel protected dari objek2: ",objek2._a)

#PRIVATE

class Hitung:
  def __init__(self):
    self. __angkaRahasia = 0
  def tampilkanHitung(self):
    self. __angkaRahasia += 1
    print(self. __angkaRahasia)

hitungan = Hitung()
hitungan.tampilkanHitung()

hitungan.tampilkanHitung()

hitungan._Hitung__angkaRahasia

#PUBLIC

class Mobil():
  def __init__(self,jendela,pintu,mesin):
    self.jendela=jendela
    self.pintu=pintu
    self.mesin=mesin

# PROTECTED

class Mobil :
    def __init__(self, jendela, pintu, mesin) :
        self._jendela = jendela
        self._pintu = pintu 
        self._mesin = mesin

audi = Mobil(4, 4, "Disel")

class Truk(Mobil) :
    def __init__ (self, jendela, pintu, mesin, tipe) :
        super().__init__(jendela, pintu, mesin) 
        self.tipebak = tipe

truk = Truk(4, 2, "Disel", "Bak Terbuka")
print(truk._mesin)
print(truk.tipebak)

#PRIVATE

class Mobil():
  def __init__(self,jendela,pintu,mesin):
    self.__jendela=jendela
    self.__pintu=pintu
    self.__mesin=mesin

#FUNGSI PRIVATE dan PUBLIC

class Pegawai:
  __nama=""
  __alamat=""
  __gaji=0

  def __init__(self,nama,alamat):
    self.__nama=nama
    self.__alamat=alamat

  def __hitungGaji(self):
    upahLembur=20000
    gajiPokok=2000000
    jumlahLembur=int(input("Total jam lembur: "))
    self.__gaji=(upahLembur*jumlahLembur)+gajiPokok

  def tampilDetail(self):
    print("\n-- Menghitung dan Menampilkan Detail Gaji Pegawai --")
    print("Nama: ",self.__nama)
    print("Alamat: ",self.__alamat)
    self.__hitungGaji()
    print("Total Gaji: ",self.__gaji)

pgw1=Pegawai("Mikasa Ackerman","Wall Rose")
pgw1.tampilDetail()

pgw2=Pegawai("Rini Kesud","Burhan Street")
pgw2.tampilDetail()

