# -*- coding: utf-8 -*-
"""PBO T8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WCb8ImT2_lcG97uZjh2bYUPqZ1r2FFKo
"""

class menuMinuman:
    def __init__(self, nama, deskripsi, harga, ukuran):
        self.nama = nama
        self.deskripsi = deskripsi
        self.harga = harga
        self.__ukuran = ukuran


mnm1 = menuMinuman('Jus Jambu', 'Jus jambu merah tanpa gula',8500, 'besar')
mnm2 = menuMinuman('Jus Alpukat Ori','Jus alpukat dengan tambahan air gula merah', 15000, 'besar')
mnm3 = menuMinuman('Jus Alpukat Xtra Milk','Jus alpukat dengan campuran susu coklat dan tamburan kepingan choco', 15000, 'kecil')
mnm4 = menuMinuman('Red & Smoothie', 'Smoothie pisang susu dan strawberry', 17500, 'sedang')
mnm5 = menuMinuman('Vanilla latte','Minuman dengan rasa vanilla khas', 10000, 'kecil')



pilihanMenu = [mnm1, mnm2, mnm3, mnm4, mnm5]
print('--Daftar Menu Healthy Fruits--')

for x in pilihanMenu:
  print('{} harga Rp. {} , {} , berukuran {}' .format(x.nama, x.harga, x.deskripsi, x._menuMinuman__ukuran))

class Buku:
    def __init__(self, judul, pengarang, tahun_terbit, penerbit):
        self.judul = judul
        self.pengarang = pengarang
        self.tahun_terbit = tahun_terbit
        self.__penerbit = penerbit


buku1 = Buku('Tenggelamnya Kapal Van Der Wijck', 'Hamka', 1938, "Haryanto")
buku2 = Buku("Matahari tersenyum llebar","fachrianshendy",2000, "Maulana")
buku3 = Buku("Piknik Seru",'Anita Hairunnisa',2009, "Erlangga")

daftarBuku = [buku1, buku2, buku3]

for x in daftarBuku:
    print(f'Buku {x.judul} karangan dari {x.pengarang} pertama kali diterbitkan tahun {x.tahun_terbit} oleh {x._Buku__penerbit}')

class Mahasiswa:
    def __init__(self, nama, nim, prodi, thn_masuk, asal):
        self.nama = nama
        self.nim = nim
        self.prodi = prodi
        self.thn_masuk = thn_masuk
        self.__asal = asal


m1 = Mahasiswa('Udin', '10120371', 'Sistem Informasi', 2020, 'Yogyakarta')
m2 = Mahasiswa('Fachrian','52107889','Sastra',2019,"Cilacap")
m3 = Mahasiswa('Shendy','2345679','Informatika',2021,"Jakarta")

dataKelas = [m1, m2, m3]

for i in dataKelas:
    print(f'{i.nama} adalah mahasiswa {i.prodi} angkatan {i.thn_masuk} dengan nim {i.nim} berasal dar kota {i._Mahasiswa__asal}')