# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uQETNuPEPzilYg6V3lnHgyscizFF9WNe
"""

#OVERLOADING

class ComputerPart():
  def __init__(self,nama,harga,kualitas): 
    self.nama = nama 
    self.harga = harga
    self.kualitas = kualitas 
  def data(self):
    print('Nama :',self.nama,', Harga :',self.harga,'Kualitas :',self.kualitas)
  
# Method Overloading
  def stok(self,stok): 
    if stok >= 5:
      print("Stok Masih Ready Banyak")
    else:
      print("Stok Hanya Tersedia Terbatas!")

pc = ComputerPart('PC GAMING SATRIA R','Rp. 7.000.000','7/10')
pc.data()
pc.stok(5) # Overloading
print()
cpu = ComputerPart('IntelCore i7 7740X 4,3GHz','Rp 2.000.000','9/10')
cpu.data()
cpu.stok(8) # Overloading
print()
ram = ComputerPart('V-Gen DDR4 SODimm PC19200/2400MHz','Rp 900.000','8/10')
ram.data()
ram.stok(3) # Overloading
print()
hdd = ComputerPart('Seagate HDD 2.5 inch 500GB','Rp 700.000','7/10')
hdd.data()
hdd.stok(2) # Overloading

#OVERRIDING

class ComputerPart():
  def __init__(self,nama,harga,kualitas): 
    self.nama = nama 
    self.harga = harga
    self.kualitas = kualitas

  def data(self): # Method Overriding
    print('Nama :',self.nama,', Harga :',self.harga,', Kualitas :',self.kualitas)

class CentralProcessingUnit(ComputerPart):
  def __init__(self,nama,harga,kualitas): 
    self.nama = nama
    self.harga = harga
    self.kualitas = kualitas

  def data(self): # Method Overriding
    print('Nama :',self.nama,', Harga :',self.harga,', Kualitas :',self.kualitas)

class RandomAccesMemory(ComputerPart): 
  def __init__(self,nama,harga,kualitas):
    self.nama = nama 
    self.harga = harga
    self.kualitas = kualitas

  def data(self): # Method Overriding
    print('Nama :',self.nama,', Harga :',self.harga,', Kualitas :',self.kualitas)

class HardDiskSATA(ComputerPart):
  def __init__(self,nama,harga,kualitas):
    self.nama = nama 
    self.harga = harga
    self.kualitas = kualitas

  def data(self): # Method Overriding
    print('Nama :',self.nama,', Harga :',self.harga,', Kualitas :',self.kualitas)


pc = ComputerPart('PC GAMING SATRIA R','Rp. 7.000.000','7/10')
pc.data()
cpu = CentralProcessingUnit('IntelCore i7 7740Xe 4,3GHz','Rp 2.000.000','9/10')
cpu.data()
ram = RandomAccesMemory('V-Gen DDR4 SODimm PC19200/2400MHz','Rp 900.000','8/10')
ram.data()
hdd = HardDiskSATA('Seagate HDD 2.5 inch 500GB','Rp 700.000','7/10')
hdd.data()